abstract: array references with accessors
author: Hans Dieter Pearcey <hdp@cpan.org>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.57
license: perl
name: Object-Array
no_index: 
  directory: 
    - inc
    - t
requires: 
  List::MoreUtils: 0
  Module::Pluggable: 0
  Scalar::Util: 0
  Sub::Exporter: 0
  Sub::Install: 0
  perl: 5.6.1
version: 0.05
